name: reports api automation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker build
        run: sudo docker build -t widgets ./widgets

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{SECRET}}

      - name: Tag and push image to GHCR
        run: |
            docker tag widgets ghcr.io/revlitix/widgets:latest
            docker push ghcr.io/revlitix/widgets:latest
